//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImdbRestService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
<<<<<<< HEAD
    public partial class ImdbEntities : DbContext, IImdbEntities
=======
    public partial class ImdbEntities : DbContext
>>>>>>> ff29b7c77d7736c3a3d6f6548c7924385153f0ea
    {
        public ImdbEntities()
            : base("name=ImdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
<<<<<<< HEAD
        public IDbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public IDbSet<InfoType> InfoTypes { get; set; }
        public IDbSet<MovieInfo> MovieInfoes { get; set; }
        public IDbSet<Movie> Movies { get; set; }
        public IDbSet<Participate> Participates { get; set; }
        public IDbSet<Person> People { get; set; }
        public IDbSet<PersonInfo> PersonInfoes { get; set; }
        public IDbSet<User> User { get; set; }
=======
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<InfoType> InfoTypes { get; set; }
        public DbSet<MovieInfo> MovieInfoes { get; set; }
        public DbSet<Movie> Movies { get; set; }
        public DbSet<Participate> Participates { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<PersonInfo> PersonInfoes { get; set; }
        public DbSet<User> User { get; set; }
>>>>>>> ff29b7c77d7736c3a3d6f6548c7924385153f0ea
    }
}
