//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImdbRestService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Participates = new HashSet<Participate>();
            this.PersonInfoes = new HashSet<PersonInfo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
    
        public virtual ICollection<Participate> Participates { get; set; }
        public virtual ICollection<PersonInfo> PersonInfoes { get; set; }
    }
}
